// <auto-generated />
namespace OZ.DBRepository.DBMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FamilyNameChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FamilyNameChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201702260601445_FamilyNameChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
